# Generated by Django 5.2.7 on 2026-03-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account_paid',
            new_name='amount_paid',
        ),
    ]
